version: "3.9"
services:
  frontend:
    image: node:20-alpine
    container_name: dashboard-frontend
    working_dir: /app
    env_file: ./frontend/.env
    environment:
      REACT_APP_API_BASE_URL: "http://localhost:3000/api"
      YARN_NETWORK_TIMEOUT: "600000"
      NPM_CONFIG_REGISTRY: "https://registry.npmjs.org/"
    command: >
      sh -lc "
        yarn config set network-timeout 600000 -g &&
        yarn config set network-concurrency 1 -g &&
        npm config set registry https://registry.npmjs.org/ &&
        yarn install &&
        yarn start
      "
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app
      - frontend_yarn:/usr/local/share/.cache/yarn
    restart: unless-stopped

volumes:
  frontend_yarn: