export const SUI_CONFIG = {
    chainId: "sui",
    symbol: "SUI",
    walletAddress: "0xb0ff460367eae42bc92566dc50135dc12eed99ead8938d18f6b8c0dd0f41b11b",
    walletId: 30,
    stakingDecimals: 9,
    liquidDecimals: 9,
    tokenDecimals: 18,
    tokens: [
        {
            id: "sui",
            name: "Sui",
            symbol: "SUI",
            decimals: 18,
            logoUrl: "https://cryptologos.cc/logos/sui-sui-logo.png?v=035",
            priceKey: "sui",
            amountFrom: "sui",
        },
        {
            id: "deep",
            name: "DEEP",
            symbol: "DEEP",
            decimals: 18,
            logoUrl: "https://s2.coinmarketcap.com/static/img/coins/200x200/33391.png",
            priceKey: "deep",
            amountFrom: "deep",
        },
    ],
};

export const APTOS_CONFIG = {
    chainId: "aptos",
    symbol: "APT",
    walletAddress: "0x7acbb55470beae407d0c897c3d1c85ba5d17955cf48ce128a05a36c2e23e2260",
    walletId: 39,
    stakingPoolAddress: "0xdb5247f859ce63dbe8940cf8773be722a60dcc594a8be9aca4b76abceb251b8e",
    decimals: 8,
    logoUrl: "https://cryptologos.cc/logos/aptos-apt-logo.png?v=035",
    priceKey: "aptos",
};

export const STATIC_CHAINS = [
    {
        id: "doge",
        name: "Dogecoin",
        symbol: "DOGE",
        decimals: 8,
        logoUrl: "https://cryptologos.cc/logos/dogecoin-doge-logo.png?v=035",
        priceKey: "dogecoin",
        wallet: "DRbbCDmZKR6p8xwx2926iM6BuPnxTS7reV",
        amount: 1500,
    },
    {
        id: "dot",
        name: "Polkadot",
        symbol: "DOT",
        decimals: 10,
        logoUrl: "https://cryptologos.cc/logos/polkadot-new-dot-logo.png?v=035",
        priceKey: "polkadot",
        wallet: "14MVcXjexqZTnqz4zSBhEbTzMdCL6mSVnVhsVMdKgx2Jvue2",
        amount: 50,
    },
    {
        id: "flow",
        name: "Flow",
        symbol: "FLOW",
        decimals: 8,
        logoUrl: "https://cryptologos.cc/logos/flow-flow-logo.png?v=035",
        priceKey: "flow",
        wallet: "14MVcXjexqZTnqz4zSBhEbTzMdCL6mSVnVhsVMdKgx2Jvue2",
        amount: 500,
    },
    {
        id: "strk",
        name: "Starknet",
        symbol: "STRK",
        decimals: 16,
        logoUrl: "https://cryptologos.cc/logos/starknet-token-strk-logo.png?v=040",
        priceKey: "starknet",
        wallet: "0x0266289d06695abf63A6a962F7671437086824F1C3C87b009e1eD3d89404Efef",
        amount: 700,
    },
    {
        id: "bvm",
        name: "BVM",
        symbol: "BVM",
        decimals: 16,
        logoUrl: "https://cryptologos.cc/logos/bitcoin-plus-xbc-logo.png?v=040",
        priceKey: "bvm",
        wallet: "0x41eD1e75d836C5C974030432fDB222f30A274f90",
        amount: 1000,
    },
    {
        id: "kraken",
        name: "KRAKEN",
        symbol: "KRAKEN",
        decimals: 16,
        logoUrl: "https://cryptologos.cc/logos/usd-coin-usdc-logo.png?v=040",
        priceKey: "usd-coin",
        wallet: "0x01",
        amount: 0,
    },
    {
        id: "nft",
        name: "NFT",
        symbol: "NFT",
        decimals: 16,
        logoUrl: "https://cryptologos.cc/logos/usd-coin-usdc-logo.png?v=040",
        priceKey: "usd-coin",
        wallet: "0x02",
        amount: 0,
    },
];
